import type { RoomTemplate } from '../types'

export const centerRoomTemplate: RoomTemplate = {
  id: 'CenterRoom',
  routeSegment: 'CenterRoom',
  name: 'Center Room',
  chatMode: 'scene',
  world: {
    width: 2300,
    height: 2700,
    spawn: { x: 1138, y: 1661 },
    backgroundColor: 0xdfe8d2,
    gridColor: 0xffffff,
  },
  camera: {
    delayMs: 300,
    offsetX: 0,
    offsetY: -72,
    clampBorders: true,
    marginX: 200,
    marginY: 200,
  },
  objects: [
    {
      id: 'plaza-separator-nw',
      kind: 'landmark',
      x: 750,
      y: 1200,
      width: 476,
      height: 508,
      opacity: 1,
      spriteAssetId: 'plaza-separator-1',
     colliders: [
    {
      offsetX: 0,
      offsetY: -46,
      width: 474,
      height: 280,
    },
    {
      offsetX: -80,
      offsetY: 160,
      width: 318,
      height: 134,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 97, width: 220, thickness: 2 },
    },
    {
      id: 'plaza-separator-ne',
      kind: 'landmark',
      x: 1600,
      y: 1200,
      width: 476,
      height: 508,
      opacity: 1,
      spriteAssetId: 'plaza-separator-2',
       colliders: [
    {
      offsetX: 0,
      offsetY: -46,
      width: 474,
      height: 280,
    },
    {
      offsetX: 80,
      offsetY: 160,
      width: 318,
      height: 134,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 97, width: 220, thickness: 2 },
    },
    {
      id: 'plaza-separator-sw',
      kind: 'landmark',
      x: 750,
      y: 2050,
      width: 476,
      height: 544,
      opacity: 1,
      spriteAssetId: 'plaza-separator-3',
       colliders: [
    {
      offsetX: 0,
      offsetY: 130,
      width: 474,
      height: 280,
    },
    {
      offsetX: -80,
      offsetY: -90,
      width: 318,
      height: 164,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 0, width: 220, thickness: 2 },
    },
    {
      id: 'plaza-separator-se',
      kind: 'landmark',
      x: 1600,
      y: 2050,
      width: 476,
      height: 544,
      opacity: 1,
      spriteAssetId: 'plaza-separator-4',
      colliders: [
    {
      offsetX: 0,
      offsetY: 130,
      width: 474,
      height: 280,
    },
    {
      offsetX: 80,
      offsetY: -90,
      width: 318,
      height: 164,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 0, width: 220, thickness: 2 },
    },

    {
      id: 'plaza-separator-e',
      kind: 'landmark',
      x: 80,
      y: 1600,
      width: 160,
      height: 1438,
      opacity: 1,
      spriteAssetId: 'plaza-separator-5',
      colliders: [
    {
      offsetX: 0,
      offsetY: 50,
      width: 160,
      height: 1300,
    },
    
  ],
      zIndexRef: { offsetX: 0, offsetY: 0, width: 220, thickness: 2 },
    },

    {
      id: 'plaza-separator-o',
      kind: 'landmark',
      x: 2220,
      y: 1600,
      width: 160,
      height: 1438,
      opacity: 1,
      spriteAssetId: 'plaza-separator-6',
      colliders: [
    {
      offsetX: 0,
      offsetY: 50,
      width: 160,
      height: 1300,
    },
    
  ],
      zIndexRef: { offsetX: 0, offsetY: 0, width: 220, thickness: 2 },
    },

        {
      id: 'castel-Wall',
      kind: 'wall',
      x: 1350,
      y: 220,
      width: 2700,
      height: 440,
      opacity: 0,
      spriteAssetId: 'plaza',
      colliders: [
    {
      offsetX: 0,
      offsetY: 0,
      width: 2700,
      height: 440,
    },
    
  ],
      zIndexRef: { offsetX: 0, offsetY: 0, width: 220, thickness: 2 },
    },

    
    
  ],
  npcs: [
    {
      entityType: 'npc',
      id: 'lobby-guide',
      label: '',
      x: 1000,
      y: 455,
      width: 128,
      height: 128,
      opacity: 1,
      spriteSheetAssetId: 'npc-mage-sheet',
      spriteSheetWidth: 512,
      spriteSheetHeight: 1280,
      spriteFrameWidth: 128,
      spriteFrameHeight: 128,
      spriteFrames: [
        { key: 'npc-mage-idle-0', row: 0, column: 0 },
        { key: 'npc-mage-idle-1', row: 0, column: 1 },
        { key: 'npc-mage-idle-2', row: 0, column: 2 },
        { key: 'npc-mage-idle-3', row: 0, column: 3 },
      ],
      spriteFrameDurationMs: 250,
      iconFrameDurationMs: 400,
      iconWarningAssetIds: [
        'npc-alert-0',
        'npc-alert-1',
        'npc-alert-2',
        'npc-alert-3',
      ],
      iconInteractionAssetIds: [
        'npc-interaction-e-0',
        'npc-interaction-e-1',
      ],
      iconOffsetX: 0,
      iconOffsetY: -200,
      iconWidth: 128,
      iconHeight: 128,
      iconWarningFillColor: 0xe85050,
      iconInteractionFillColor: 0x6354ff,
      collider: {
        offsetX: 0,
        offsetY: -12,
        width: 68,
        height: 24,
      },
      zIndexRef: {
        offsetX: 0,
        offsetY: -12,
        width: 68,
        thickness: 2,
      },
      warningArea: {
        offsetX: 0,
        offsetY: -70,
        width: 750,
        height: 750,
      },
      interactionArea: {
        offsetX: 0,
        offsetY: -54,
        width: 350,
        height: 350,
      },
      interactionId: 'lobby-guide',
      dialogueId: 'lobby-guide-intro',
    },
  ],
  teleports: [
    {
      entityType: 'teleport',
      id: 'room-1909-teleport',
      label: '',
      x: 1097,
      y: 366,
      width: 220,
      height: 104,
      fillColor: 0x936d6d,
      strokeColor: 0xd8c4c4,
      opacity: 0.34,
      iconFrameDurationMs: 400,
      iconWarningAssetIds: [
        'npc-alert-0',
        'npc-alert-1',
        'npc-alert-2',
        'npc-alert-3',
      ],
      iconInteractionAssetIds: [
        'npc-interaction-e-0',
        'npc-interaction-e-1',
      ],
      iconOffsetX: 0,
      iconOffsetY: -72,
      iconWidth: 96,
      iconHeight: 96,
      iconWarningFillColor: 0xe85050,
      iconInteractionFillColor: 0x6354ff,
      warningArea: {
        offsetX: 0,
        offsetY: 120,
        width: 320,
        height: 240,
      },
      interactionArea: {
        offsetX: 0,
        offsetY: 120,
        width: 240,
        height: 176,
      },
      interactionId: 'tp-room-1909',
      teleportTarget: {
        templateId: 'Room_1909',
        position: { x: 1000, y: 1600 },
      },
    },
  ],
}
