import type { RoomTemplate } from '../types'

export const centerRoomTemplate: RoomTemplate = {
  id: 'CenterRoom',
  routeSegment: 'CenterRoom',
  name: 'Center Room',
  chatMode: 'scene',
  world: {
    width: 1920,
    height: 1080,
    spawn: { x: 261, y: 500 },
    backgroundColor: 0xdfe8d2,
    gridColor: 0xffffff,
  },
  camera: {
    delayMs: 300,
    offsetX: 0,
    offsetY: -72,
    clampBorders: true,
    marginX: 200,
    marginY: 200,
  },
  objects: [
    {
      id: 'castle-wall',
      kind: 'wall',
      x: 960,
      y: 100,
      width: 1920,
      height: 200,
      opacity: 0,
      colliders: [
        {
          offsetX: 0,
          offsetY: 0,
          width: 1920,
          height: 200,
        },
      ],
      zIndexRef: { offsetX: 0, offsetY: 100, width: 1920, thickness: 2 },
    },
  ],
  npcs: [],
  teleports: [
    {
      entityType: 'teleport',
      id: 'room-1909-teleport',
      label: '',
      x: 261,
      y: 223,
      width: 202,
      height: 192,
      spriteAssetId: 'tp-center-room-1',
      fillColor: 0x936d6d,
      strokeColor: 0xd8c4c4,
      opacity: 1,
      iconFrameDurationMs: 400,
      iconWarningAssetIds: [
        'npc-alert-0',
        'npc-alert-1',
        'npc-alert-2',
        'npc-alert-3',
      ],
      iconInteractionAssetIds: [
        'npc-interaction-e-0',
        'npc-interaction-e-1',
      ],
      iconOffsetX: 0,
      iconOffsetY: -72,
      iconWidth: 96,
      iconHeight: 96,
      iconWarningFillColor: 0xe85050,
      iconInteractionFillColor: 0x6354ff,
      warningArea: {
        offsetX: 0,
        offsetY: 70,
        width: 320,
        height: 240,
      },
      interactionArea: {
        offsetX: 0,
        offsetY: 70,
        width: 240,
        height: 176,
      },
      interactionId: 'tp-room-1909',
      teleportTarget: {
        templateId: 'Room_1909',
        position: { x: 1000, y: 1600 },
      },
    },
  ],
}
