import type { RoomTemplate } from '../types'

export const mazmorraDemoTemplate: RoomTemplate = {
  id: 'mazmorra_demo',
  routeSegment: 'mazmorra_demo',
  name: 'Mazmorra Demo',
  chatMode: 'scene',
  world: {
    width: 4500,
    height: 1080,
    spawn: { x: 333, y: 604 },
    backgroundColor: 0x101010,
    gridColor: 0xffffff,
  },
  camera: {
    delayMs: 300,
    offsetX: 0,
    offsetY: -72,
    clampBorders: true,
    marginX: 200,
    marginY: 200,
  },
  objects: [],
  enemies: [
    {
      entityType: 'enemy',
      id: 'NPC_ENEMIGO',
      label: 'Rival',
      posicion_relativa_X: 2224,
      posicion_relativa_Y: 468,
      ancho_de_patrullaje_: 1000,
      alto_de_patrullaje_: 1000,
      velocidad_de_patrullaje_: 72,
      nivel_enemigo_: 0,
      ancho_area_interaccion_directa_: 300,
      alto_area_interaccion_directa_: 300,
    },
  ],
  npcs: [
    {
      entityType: 'npc',
      id: 'mazmorra-guide',
      label: '',
      x: 728,
      y: 600,
      width: 128,
      height: 128,
      opacity: 1,
      spriteSheetAssetId: 'npc-mage-sheet',
      spriteSheetWidth: 512,
      spriteSheetHeight: 1280,
      spriteFrameWidth: 128,
      spriteFrameHeight: 128,
      spriteFrames: [
        { key: 'npc-mage-idle-0', row: 0, column: 0 },
        { key: 'npc-mage-idle-1', row: 0, column: 1 },
        { key: 'npc-mage-idle-2', row: 0, column: 2 },
        { key: 'npc-mage-idle-3', row: 0, column: 3 },
      ],
      spriteFrameDurationMs: 250,
      iconFrameDurationMs: 400,
      iconWarningAssetIds: [
        'npc-alert-0',
        'npc-alert-1',
        'npc-alert-2',
        'npc-alert-3',
      ],
      iconInteractionAssetIds: [
        'npc-interaction-e-0',
        'npc-interaction-e-1',
      ],
      iconOffsetX: 0,
      iconOffsetY: -200,
      iconWidth: 128,
      iconHeight: 128,
      iconWarningFillColor: 0xe85050,
      iconInteractionFillColor: 0x6354ff,
      collider: {
        offsetX: 0,
        offsetY: -12,
        width: 68,
        height: 24,
      },
      zIndexRef: {
        offsetX: 0,
        offsetY: -12,
        width: 68,
        thickness: 2,
      },
      warningArea: {
        offsetX: 0,
        offsetY: -70,
        width: 750,
        height: 750,
      },
      interactionArea: {
        offsetX: 0,
        offsetY: -54,
        width: 350,
        height: 350,
      },
      interactionId: 'mazmorra-guide',
      dialogueId: 'lobby-guide-intro',
    },
  ],
  teleports: [
    {
      entityType: 'teleport',
      id: 'room-1909-teleport',
      label: '',
      x: 4000,
      y: 604,
      width: 202,
      height: 192,
      spriteAssetId: 'tp-room-1909-1',
      spriteHoverAssetId: 'tp-room-1909-1-hover',
      fillColor: 0x936d6d,
      strokeColor: 0xd8c4c4,
      opacity: 1,
      iconFrameDurationMs: 400,
      iconWarningAssetIds: [
        'npc-alert-0',
        'npc-alert-1',
        'npc-alert-2',
        'npc-alert-3',
      ],
      iconInteractionAssetIds: [
        'npc-interaction-e-0',
        'npc-interaction-e-1',
      ],
      iconOffsetX: 0,
      iconOffsetY: -220,
      iconWidth: 96,
      iconHeight: 96,
      iconWarningFillColor: 0xe85050,
      iconInteractionFillColor: 0x6354ff,
      warningArea: {
        offsetX: 0,
        offsetY: 70,
        width: 320,
        height: 240,
      },
      interactionArea: {
        offsetX: 0,
        offsetY: 70,
        width: 240,
        height: 176,
      },
      interactionId: 'tp-room-1909',
      teleportTarget: {
        templateId: 'Room_1909',
        position: { x: 1000, y: 1600 },
      },
    },
  ],
}
