import type { RoomTemplate } from '../types'

export const room1909Template: RoomTemplate = {
  id: 'Room_1909',
  routeSegment: 'Room_1909',
  name: 'Lobby Garden 1909',
  chatMode: 'scene',
  world: {
    width: 2000,
    height: 2000,
    spawn: { x: 1000, y: 1600 },
    backgroundColor: 0xdfe8d2,
    gridColor: 0xffffff,
  },
  camera: {
    delayMs: 300,
    offsetX: 0,
    offsetY: -72,
    clampBorders: true,
    marginX: 200,
    marginY: 200,
  },
  objects: [
    {
      id: 'plaza-separator-nw',
      kind: 'landmark',
      x: 690,
      y: 700,
      width: 476,
      height: 508,
      opacity: 1,
      spriteAssetId: 'plaza-separator-1',
     colliders: [
    {
      offsetX: 0,
      offsetY: -46,
      width: 474,
      height: 280,
    },
    {
      offsetX: -80,
      offsetY: 160,
      width: 318,
      height: 134,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 97, width: 220, thickness: 2 },
    },
    {
      id: 'plaza-separator-ne',
      kind: 'landmark',
      x: 1310,
      y: 700,
      width: 476,
      height: 508,
      opacity: 1,
      spriteAssetId: 'plaza-separator-2',
       colliders: [
    {
      offsetX: 0,
      offsetY: -46,
      width: 474,
      height: 280,
    },
    {
      offsetX: 80,
      offsetY: 160,
      width: 318,
      height: 134,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 97, width: 220, thickness: 2 },
    },
    {
      id: 'plaza-separator-sw',
      kind: 'landmark',
      x: 690,
      y: 1250,
      width: 476,
      height: 544,
      opacity: 1,
      spriteAssetId: 'plaza-separator-3',
       colliders: [
    {
      offsetX: 0,
      offsetY: 130,
      width: 474,
      height: 280,
    },
    {
      offsetX: -80,
      offsetY: -90,
      width: 318,
      height: 164,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 0, width: 220, thickness: 2 },
    },
    {
      id: 'plaza-separator-se',
      kind: 'landmark',
      x: 1310,
      y: 1250,
      width: 476,
      height: 544,
      opacity: 1,
      spriteAssetId: 'plaza-separator-4',
      colliders: [
    {
      offsetX: 0,
      offsetY: 130,
      width: 474,
      height: 280,
    },
    {
      offsetX: 80,
      offsetY: -90,
      width: 318,
      height: 164,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 0, width: 220, thickness: 2 },
    },
    {
      id: 'spawn-ring',
      kind: 'zone',
      x: 1000,
      y: 1600,
      width: 420,
      height: 180,
      label: 'Ingreso',
      fillColor: 0xf6d37f,
      strokeColor: 0xfff7d2,
      opacity: 0.2,
      collider: { offsetX: 0, offsetY: 0, width: 0, height: 0 },
      zIndexRef: { offsetX: 0, offsetY: 20, width: 100, thickness: 2 },
    },
  ],
}
