import type { RoomTemplate } from '../types'

export const room1909Template: RoomTemplate = {
  id: 'Room_1909',
  routeSegment: 'Room_1909',
  name: 'Lobby Garden 1909',
  chatMode: 'scene',
  world: {
    width: 2000,
    height: 2000,
    spawn: { x: 1000, y: 1600 },
    backgroundColor: 0xdfe8d2,
    gridColor: 0xffffff,
  },
  camera: {
    delayMs: 300,
    offsetX: 0,
    offsetY: -72,
    clampBorders: true,
    marginX: 200,
    marginY: 200,
  },
  objects: [
    {
      id: 'plaza-separator-nw',
      kind: 'landmark',
      x: 690,
      y: 700,
      width: 476,
      height: 508,
      opacity: 1,
      spriteAssetId: 'plaza-separator-1',
     colliders: [
    {
      offsetX: 0,
      offsetY: -46,
      width: 474,
      height: 280,
    },
    {
      offsetX: -80,
      offsetY: 160,
      width: 318,
      height: 134,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 97, width: 220, thickness: 2 },
    },
    {
      id: 'plaza-separator-ne',
      kind: 'landmark',
      x: 1310,
      y: 700,
      width: 476,
      height: 508,
      opacity: 1,
      spriteAssetId: 'plaza-separator-2',
       colliders: [
    {
      offsetX: 0,
      offsetY: -46,
      width: 474,
      height: 280,
    },
    {
      offsetX: 80,
      offsetY: 160,
      width: 318,
      height: 134,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 97, width: 220, thickness: 2 },
    },
    {
      id: 'plaza-separator-sw',
      kind: 'landmark',
      x: 690,
      y: 1250,
      width: 476,
      height: 544,
      opacity: 1,
      spriteAssetId: 'plaza-separator-3',
       colliders: [
    {
      offsetX: 0,
      offsetY: 130,
      width: 474,
      height: 280,
    },
    {
      offsetX: -80,
      offsetY: -90,
      width: 318,
      height: 164,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 0, width: 220, thickness: 2 },
    },
    {
      id: 'plaza-separator-se',
      kind: 'landmark',
      x: 1310,
      y: 1250,
      width: 476,
      height: 544,
      opacity: 1,
      spriteAssetId: 'plaza-separator-4',
      colliders: [
    {
      offsetX: 0,
      offsetY: 130,
      width: 474,
      height: 280,
    },
    {
      offsetX: 80,
      offsetY: -90,
      width: 318,
      height: 164,
    },
  ],
      zIndexRef: { offsetX: 0, offsetY: 0, width: 220, thickness: 2 },
    },
    {
      id: 'spawn-ring',
      kind: 'zone',
      x: 1000,
      y: 1600,
      width: 420,
      height: 180,
      label: 'Ingreso',
      fillColor: 0xf6d37f,
      strokeColor: 0xfff7d2,
      opacity: 0.2,
      collider: { offsetX: 0, offsetY: 0, width: 0, height: 0 },
      zIndexRef: { offsetX: 0, offsetY: 20, width: 100, thickness: 2 },
    },
  ],
  npcs: [
    {
      id: 'lobby-guide',
      label: '',
      x: 1000,
      y: 1000,
      width: 128,
      height: 128,
      opacity: 1,
      spriteSheetAssetId: 'npc-mage-sheet',
      spriteSheetWidth: 512,
      spriteSheetHeight: 1280,
      spriteFrameWidth: 128,
      spriteFrameHeight: 128,
      spriteFrames: [
        { key: 'npc-mage-idle-0', row: 0, column: 0 },
        { key: 'npc-mage-idle-1', row: 0, column: 1 },
        { key: 'npc-mage-idle-2', row: 0, column: 2 },
        { key: 'npc-mage-idle-3', row: 0, column: 3 },
      ],
      spriteFrameDurationMs: 250,
      iconFrameDurationMs: 400,
      iconWarningAssetIds: [
        'npc-alert-0',
        'npc-alert-1',
        'npc-alert-2',
        'npc-alert-3',
      ],
      iconInteractionAssetIds: [
        'npc-interaction-e-0',
        'npc-interaction-e-1',
      ],
      iconOffsetX: 0,
      iconOffsetY: -200,
      iconWidth: 128,
      iconHeight: 128,
      iconWarningFillColor: 0xe85050,
      iconInteractionFillColor: 0x6354ff,
      collider: {
        offsetX: 0,
        offsetY: -12,
        width: 68,
        height: 24,
      },
      zIndexRef: {
        offsetX: 0,
        offsetY: -12,
        width: 68,
        thickness: 2,
      },
      warningArea: {
        offsetX: 0,
        offsetY: -70,
        width: 750,
        height: 750,
      },
      interactionArea: {
        offsetX: 0,
        offsetY: -54,
        width: 350,
        height: 350,
      },
      interactionId: 'lobby-guide',
      dialogueId: 'lobby-guide-intro',
    },
  ],
}
