import type { RoomTemplate } from '../types'

const TAVERN_COLLISIONS_ENABLED = true;

function createTavernWallCollider(width: number, height: number) {
  return {
    offsetX: 0,
    offsetY: 0,
    width: TAVERN_COLLISIONS_ENABLED ? width : 0,
    height: TAVERN_COLLISIONS_ENABLED ? height : 0,
  }
}

export const tavernTemplate: RoomTemplate = {
  id: 'Tavern',
  routeSegment: 'Tavern',
  name: 'La Taberna',
  chatMode: 'scene',
  world: {
    width: 3000,
    height: 3000,
    spawn: { x: 1500, y: 1500 },
    backgroundColor: 0x171717,
    gridColor: 0xffffff,
  },
  camera: {
    delayMs: 300,
    offsetX: 0,
    offsetY: -72,
    clampBorders: true,
    marginX: 200,
    marginY: 200,
  },
  // Muros de colision trazados sobre las zonas #FF0000 de TavernDesign.png.
  objects: [
    {
      id: 'tavern-wall-outer-top',
      kind: 'wall',
      x: 1500,
      y: 350,
      width: 2400,
      height: 100,
      opacity: 0,
      collider: createTavernWallCollider(2400, 100),
    },
    {
      id: 'tavern-wall-outer-left',
      kind: 'wall',
      x: 350,
      y: 1500,
      width: 100,
      height: 2400,
      opacity: 0,
      collider: createTavernWallCollider(100, 2400),
    },
    {
      id: 'tavern-wall-outer-right',
      kind: 'wall',
      x: 2650,
      y: 1500,
      width: 100,
      height: 2400,
      opacity: 0,
      collider: createTavernWallCollider(100, 2400),
    },
    {
      id: 'tavern-wall-upper-divider-north',
      kind: 'wall',
      x: 1550,
      y: 500,
      width: 100,
      height: 200,
      opacity: 0,
      collider: createTavernWallCollider(100, 200),
    },
    {
      id: 'tavern-wall-upper-divider-south',
      kind: 'wall',
      x: 1550,
      y: 850,
      width: 100,
      height: 100,
      opacity: 0,
      collider: createTavernWallCollider(100, 100),
    },
    {
      id: 'tavern-wall-middle-left',
      kind: 'wall',
      x: 550,
      y: 950,
      width: 300,
      height: 100,
      opacity: 0,
      collider: createTavernWallCollider(300, 100),
    },
    {
      id: 'tavern-wall-middle-center',
      kind: 'wall',
      x: 1500,
      y: 950,
      width: 800,
      height: 100,
      opacity: 0,
      collider: createTavernWallCollider(800, 100),
    },
    {
      id: 'tavern-wall-middle-right',
      kind: 'wall',
      x: 2450,
      y: 950,
      width: 300,
      height: 100,
      opacity: 0,
      collider: createTavernWallCollider(300, 100),
    },
    {
      id: 'tavern-wall-lower-right',
      kind: 'wall',
      x: 2450,
      y: 1750,
      width: 300,
      height: 100,
      opacity: 0,
      collider: createTavernWallCollider(300, 100),
    },
    {
      id: 'tavern-wall-mission-room-north',
      kind: 'wall',
      x: 1900,
      y: 1750,
      width: 200,
      height: 100,
      opacity: 0,
      collider: createTavernWallCollider(200, 100),
    },
    {
      id: 'tavern-wall-mission-room-west-upper',
      kind: 'wall',
      x: 1850,
      y: 1950,
      width: 100,
      height: 300,
      opacity: 0,
      collider: createTavernWallCollider(100, 300),
    },
    {
      id: 'tavern-wall-mission-room-west-lower',
      kind: 'wall',
      x: 1850,
      y: 2450,
      width: 100,
      height: 300,
      opacity: 0,
      collider: createTavernWallCollider(100, 300),
    },
    {
      id: 'tavern-wall-bottom-left',
      kind: 'wall',
      x: 900,
      y: 2650,
      width: 1000,
      height: 100,
      opacity: 0,
      collider: createTavernWallCollider(1000, 100),
    },
    {
      id: 'tavern-wall-bottom-right',
      kind: 'wall',
      x: 2200,
      y: 2650,
      width: 800,
      height: 100,
      opacity: 0,
      collider: createTavernWallCollider(800, 100),
    },
  ],
  npcs: [
    {
      entityType: 'npc',
      id: 'tavern-weapon-shopkeeper',
      label: 'Mercader de armas',
      merchant: {
        type: 'shop',
        categories: ['weapons'],
      },
      x: 2050,
      y: 590,
      width: 128,
      height: 128,
      opacity: 1,
      spriteSheetAssetId: 'npc-mage-sheet',
      spriteSheetWidth: 512,
      spriteSheetHeight: 1280,
      spriteFrameWidth: 128,
      spriteFrameHeight: 128,
      spriteFrames: [
        { key: 'tavern-weapon-shopkeeper-idle-0', row: 0, column: 0 },
        { key: 'tavern-weapon-shopkeeper-idle-1', row: 0, column: 1 },
        { key: 'tavern-weapon-shopkeeper-idle-2', row: 0, column: 2 },
        { key: 'tavern-weapon-shopkeeper-idle-3', row: 0, column: 3 },
      ],
      spriteFrameDurationMs: 250,
      iconFrameDurationMs: 400,
      iconWarningAssetIds: [
        'npc-alert-0',
        'npc-alert-1',
        'npc-alert-2',
        'npc-alert-3',
      ],
      iconInteractionAssetIds: [
        'npc-interaction-e-0',
        'npc-interaction-e-1',
      ],
      iconOffsetX: 0,
      iconOffsetY: -200,
      iconWidth: 128,
      iconHeight: 128,
      iconWarningFillColor: 0xe85050,
      iconInteractionFillColor: 0x6354ff,
      collider: {
        offsetX: 0,
        offsetY: -12,
        width: 68,
        height: 24,
      },
      zIndexRef: {
        offsetX: 0,
        offsetY: -12,
        width: 68,
        thickness: 2,
      },
      warningArea: {
        offsetX: 0,
        offsetY: 130,
        width: 600,
        height: 500,
      },
      interactionArea: {
        offsetX: 0,
        offsetY: 150,
        width: 450,
        height: 350,
      },
      interactionId: 'tavern-weapon-shopkeeper',
    },
  ],
  teleports: [],
  enemies: [],
}
