export const clientEvents = {
  connectToGame: 'connect_to_game',
  completeOnboarding: 'complete_onboarding',
  joinRoom: 'join_room',
  navigateTo: 'navigate_to',
  stopNavigation: 'stop_navigation',
  setMovementInput: 'set_movement_input',
  updateSkin: 'update_skin',
  updateAudioSettings: 'update_audio_settings',
  updateInventory: 'update_inventory',
  addFriend: 'add_friend',
  respondFriendRequest: 'respond_friend_request',
  removeFriend: 'remove_friend',
  requestSocialState: 'request_social_state',
  inviteToParty: 'invite_to_party',
  respondPartyInvite: 'respond_party_invite',
  requestEnemyCombat: 'request_enemy_combat',
  respondEnemyCombatSupport: 'respond_enemy_combat_support',
  fleeEnemyCombat: 'flee_enemy_combat',
  respondPartyLeaderFollow: 'respond_party_leader_follow',
  leaveParty: 'leave_party',
  promotePartyLeader: 'promote_party_leader',
  requestPartyState: 'request_party_state',
  setTypingState: 'set_typing_state',
  sendChatMessage: 'send_chat_message',
  ping: 'ping',
} as const

export const serverEvents = {
  connectionAccepted: 'connection_accepted',
  roomJoined: 'room_joined',
  roomState: 'room_state',
  roomEnemiesState: 'room_enemies_state',
  roomEnemyCombatState: 'room_enemy_combat_state',
  playerJoined: 'player_joined',
  playerMoved: 'player_moved',
  playerLeft: 'player_left',
  socialState: 'social_state',
  friendRequestReceived: 'friend_request_received',
  partyState: 'party_state',
  partyInviteReceived: 'party_invite_received',
  enemyCombatSupportInviteReceived: 'enemy_combat_support_invite_received',
  partyLeaderFollowRequested: 'party_leader_follow_requested',
  activityNotice: 'activity_notice',
  roomTransitionRequested: 'room_transition_requested',
  typingStateChanged: 'typing_state_changed',
  chatMessage: 'chat_message',
  serverError: 'server_error',
} as const
